# -*- coding: utf-8 -*-
"""WeCom channel streaming reply logic."""

import asyncio
import logging
from typing import TYPE_CHECKING

from wecom_aibot_sdk import generate_req_id
from wecom_aibot_sdk.types import WsFrame
from agentscope_runtime.engine.schemas.agent_schemas import RunStatus

from ..base import ContentType
from .constants import (
    STREAM_TIMEOUT,
    MAX_STREAM_CONTENT_LENGTH,
    THINKING_MESSAGE,
    TIMEOUT_MESSAGE,
    ERROR_MESSAGE,
)

if TYPE_CHECKING:
    from agentscope_runtime.engine.schemas.agent_schemas import (
        AgentRequest,
    )
    from .channel import WecomChannel

logger = logging.getLogger(__name__)


async def stream_reply(
    channel: "WecomChannel",
    request: "AgentRequest",
    frame: WsFrame,
    req_id: str,
) -> None:
    """Call Agent and reply to user with streaming.

    Args:
        channel: WecomChannel instance.
        request: AgentRequest to process.
        frame: Raw WsFrame from SDK.
        req_id: Request ID from WeCom.
    """
    if not channel.client:
        return

    stream_id = generate_req_id("stream")

    # Send thinking placeholder frame
    await send_stream_frame(
        channel,
        frame,
        req_id,
        stream_id,
        THINKING_MESSAGE,
        finish=False,
    )

    accumulated = ""
    has_final = False
    event_count = 0

    try:
        async for event in channel._process(request):  # pylint: disable=protected-access  # noqa: E501
            event_count += 1
            obj = getattr(event, "object", None)
            status = getattr(event, "status", None)
            ev_type = getattr(event, "type", None)

            logger.debug(
                "[WeCom] Event #%d: object=%s status=%s type=%s",
                event_count,
                obj,
                status,
                ev_type,
            )

            if obj == "message" and status == RunStatus.Completed:
                parts = channel._message_to_content_parts(event)  # pylint: disable=protected-access  # noqa: E501
                logger.debug(
                    "[WeCom] Message completed: parts_count=%d",
                    len(parts),
                )
                for part in parts:
                    if part.type == ContentType.TEXT and part.text:
                        accumulated += part.text
                        # Push intermediate frames in real-time
                        await send_stream_frame(
                            channel,
                            frame,
                            req_id,
                            stream_id,
                            accumulated,
                            finish=False,
                        )

        # Send final frame
        logger.info(
            "[WeCom] Stream complete: event_count=%d accumulated_len=%d",
            event_count,
            len(accumulated),
        )
        final_text = accumulated or "Message received."
        await send_stream_frame(
            channel,
            frame,
            req_id,
            stream_id,
            final_text,
            finish=True,
        )
        has_final = True

    except Exception as exc:
        logger.error(
            "[WeCom] Streaming reply error: %s",
            exc,
            exc_info=True,
        )
        if not has_final:
            await send_stream_frame(
                channel,
                frame,
                req_id,
                stream_id,
                ERROR_MESSAGE,
                finish=True,
            )


async def send_stream_frame(
    channel: "WecomChannel",
    frame: WsFrame,
    req_id: str,
    stream_id: str,
    content: str,
    finish: bool,
) -> None:
    """Send one streaming message frame via SDK reply_stream.

    Args:
        channel: WecomChannel instance.
        frame: Raw WsFrame from SDK.
        req_id: Request ID from WeCom.
        stream_id: Stream ID generated by SDK.
        content: Message content to send.
        finish: Whether this is the final frame.
    """
    if not channel.client:
        return

    # Truncate content per official docs limit
    content_bytes = content.encode("utf-8")
    if len(content_bytes) > MAX_STREAM_CONTENT_LENGTH:
        content = content_bytes[:MAX_STREAM_CONTENT_LENGTH].decode(
            "utf-8",
            errors="ignore",
        )
        logger.warning(
            "[WeCom] Stream content exceeds limit, truncated (req_id=%s)",
            req_id,
        )

    try:
        await channel.client.reply_stream(frame, stream_id, content, finish)
        logger.debug(
            "[WeCom] Sent stream frame: finish=%s, len=%d",
            finish,
            len(content),
        )
    except Exception as exc:
        logger.error(
            "[WeCom] Failed to send stream frame: %s",
            exc,
            exc_info=True,
        )


async def dispatch_with_timeout(
    channel: "WecomChannel",
    request: "AgentRequest",
    frame: WsFrame,
    req_id: str,
) -> None:
    """Dispatch message with timeout handling.

    Args:
        channel: WecomChannel instance.
        request: AgentRequest to process.
        frame: Raw WsFrame from SDK.
        req_id: Request ID from WeCom.
    """
    try:
        await asyncio.wait_for(
            stream_reply(channel, request, frame, req_id),
            timeout=STREAM_TIMEOUT,
        )
    except asyncio.TimeoutError:
        logger.error("[WeCom] Request timeout (req_id=%s)", req_id)
        stream_id = generate_req_id("stream")
        await send_stream_frame(
            channel,
            frame,
            req_id,
            stream_id,
            TIMEOUT_MESSAGE,
            finish=True,
        )
